name: Ubuntu CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ['8.10.1']
        cabal: ['3.4.0.0']
        
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup Haskell
      uses: haskell/actions/setup@v1
      id: setup-haskell-cabal
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}
        
    - name: Freeze
      run: |
        cabal freeze
    - name: Cache cabal
      uses: actions/cache@v2
      id: cache-cabal
      with:
        path: '~/.cabal'
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('/src/Main.hs') }}-a
        
    - name: Cache dist
      uses: actions/cache@v2
      id: cache-bin
      with:
        path: '/dist-newstyle/'
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('/src/Main.hs') }}-b
    
    - name: cabal update and build
      run: cabal v2-build --enable-tests
    
    - name : make directory
      run: |
            mkdir binary
            mkdir binary/haskell-libs/
            mkdir binary/c-libs/
            ls
            
    - name: move GHC libs and configs
      run: |
            mkdir binary/haskell-libs/ghc-packages/
            cd ${{ steps.setup-haskell-cabal.outputs.ghc-path }}
            cd ..
            cd lib
            cp -r ghc-${{ matrix.ghc }}/* /home/runner/work/tidal-gui/tidal-gui/binary/haskell-libs/ghc-packages
            
    - name: move installed packages
      run: | 
            mkdir binary/haskell-libs/packages/
            cp -r ${{ steps.setup-haskell-cabal.outputs.cabal-store }}/ghc-${{ matrix.ghc }}/* binary/haskell-libs/packages
            ls binary/haskell-libs/packages
   
    - name: change paths in config files (GHC)
      run: |
            mv /home/runner/work/tidal-gui/tidal-gui/binary/haskell-libs/ghc-packages/package.conf.d /home/runner/work/tidal-gui/tidal-gui/binary/haskell-libs/package.conf.d
            sed -i 's/\/opt\/ghc\/${{ matrix.ghc }}\/lib\/ghc-${{ matrix.ghc }}/${pkgroot}\/ghc-packages/g' /home/runner/work/tidal-gui/tidal-gui/binary/haskell-libs/package.conf.d/*
     
    - name: change paths in config files (cabal)
      run: |
            mv /home/runner/work/tidal-gui/tidal-gui/binary/haskell-libs/packages/package.db /home/runner/work/tidal-gui/tidal-gui/binary/haskell-libs/package.db
            sed -i 's/\/home\/runner\/.cabal\/store\/ghc-${{ matrix.ghc }}/${pkgroot}\/packages/g' /home/runner/work/tidal-gui/tidal-gui/binary/haskell-libs/package.db/*
   
    - name: move ghc settings etc
      run: |
            mv /home/runner/work/tidal-gui/tidal-gui/binary/haskell-libs/ghc-packages/settings /home/runner/work/tidal-gui/tidal-gui/binary/haskell-libs/settings
            mv /home/runner/work/tidal-gui/tidal-gui/binary/haskell-libs/ghc-packages/platformConstants /home/runner/work/tidal-gui/tidal-gui/binary/haskell-libs/platformConstants
            mv /home/runner/work/tidal-gui/tidal-gui/binary/haskell-libs/ghc-packages/llvm-targets /home/runner/work/tidal-gui/tidal-gui/binary/haskell-libs/llvm-targets
            mv /home/runner/work/tidal-gui/tidal-gui/binary/haskell-libs/ghc-packages/llvm-passes /home/runner/work/tidal-gui/tidal-gui/binary/haskell-libs/llvm-passes
    - name: ghc-pkg recache
      run: |
            ghc-pkg --package-db=/home/runner/work/tidal-gui/tidal-gui/binary/haskell-libs/package.conf.d recache
            ghc-pkg --package-db=/home/runner/work/tidal-gui/tidal-gui/binary/haskell-libs/package.db recache
            ghc-pkg --package-db=/home/runner/work/tidal-gui/tidal-gui/binary/haskell-libs/package.conf.d --package-db=/home/runner/work/tidal-gui/tidal-gui/binary/haskell-libs/package.db check
   
    - name: move c-libs
      run: ls /usr/lib/x86_64-linux-gnu/
   
    - name: remove unneccessary libs 
      run: |
            cd /home/runner/work/tidal-gui/tidal-gui/binary/haskell-libs/ghc-packages
            rm -r ghc-${{ matrix.ghc }}
            rm -r Cabal-*
            
    - name: fake gcc
      run: |
            mkdir binary/bin
            cp -r fake_gcc.sh binary/bin/fake_gcc.sh
            sed -i 's/cc/bin\/fake_gcc.sh/g' /home/runner/work/tidal-gui/tidal-gui/binary/haskell-libs/settings
   
    - name: move static
      run: cp -r static binary/static
   
    - name: move executable
      run: cp -r dist-newstyle/build/x86_64-linux/ghc-${{ matrix.ghc }}/tidal-gui-0.1.0.0/x/tidal-gui/build/tidal-gui/tidal-gui binary/tidal-gui
  
    - uses: actions/upload-artifact@v2
      with:
        name: tidal-gui
        path: /home/runner/work/tidal-gui/tidal-gui/binary
